apiVersion: v1
kind: Pod
metadata:
  name: hello-kube-pod
  labels:
    name: hello-kube-pod
spec:
  containers:
    - name: hello-kube
      image: fhsinchy/hello-kube
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
      ports:
        - containerPort: 81
