apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
spec:
  selector:
    matchLabels:
      app: notes-api
  template:
    metadata:
      labels:
        app: notes-api
    spec:
      replicas: 3
      containers:
      - name: notes-api
        image: fhsinchy/notes-api
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
