apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: notes-api
  template:
    metadata:
      labels:
        component: notes-api
    spec:
      containers:
        - name: notes-api
          image: fhsinchy/notes-api
          resources:
            limits:
              memory: "64Mi"
              cpu: "125m"
          ports:
            - containerPort: 3000
          env:
            - name: DB_CONNECTION
              value: pg
            - name: DB_HOST
              value: notes-database-service
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_DATABASE
              value: notesdb
            - name: DB_PASSWORD
              value: 63eaQB9wtLqmNBpg
